version: "3.9"

services:
  api:
    build:
      context: ./task-manager-back
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      APP_UPLOAD_DIR: /data/uploads
    volumes:
      - uploads:/data/uploads
    ports:
      - "8080:8080"
    restart: unless-stopped

  web:
    build:
      context: ./task-manager-front
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  uploads:
