version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-task-manager
    restart: unless-stopped

    environment:
      POSTGRES_USER: Inerio
      POSTGRES_PASSWORD: 1234          # change in production!
      POSTGRES_DB: TaskManagerDB
      PGDATA: /data/postgres

    volumes:
      - db_data:/data/postgres         # persistent volume

    ports:
      - "5432:5432"                    

    networks:
      - backend                        # internal network for API + DB

networks:
  backend:
    driver: bridge                     # isolated Docker network

volumes:
  db_data:                             
